Repository DmytroProg/SocialNetworkProject, pull requests merged in 2024-11, with the labels that each got.

#11 Comment model
  SocialNetwork/SocialNetwork.Core/Models/Comment.cs
Labels: Rejected

#17 Sn services user
  SocialNetwork/SocialNetwork.API/Program.cs
  SocialNetwork/SocialNetwork.Core/Interfaces/IRepository.cs
  SocialNetwork/SocialNetwork.Core/Interfaces/IUserService.cs
  SocialNetwork/SocialNetwork.Core/Services/UserService.cs
  SocialNetwork/SocialNetwork.Core/SocialNetwork.Core.csproj
  SocialNetwork/SocialNetwork.Storage/Repository.cs
Labels: Rejected

#12 Repository
  SocialNetwork/SocialNetwork.API/Controllers/UserController.cs
  SocialNetwork/SocialNetwork.API/Program.cs
  SocialNetwork/SocialNetwork.API/SocialNetwork.API.csproj
  SocialNetwork/SocialNetwork.API/appsettings.json
  SocialNetwork/SocialNetwork.Core/Interfaces/IRepository.cs
  SocialNetwork/SocialNetwork.Core/Models/Comment.cs
  SocialNetwork/SocialNetwork.Core/SocialNetwork.Core.csproj
  SocialNetwork/SocialNetwork.Storage/Data/Repository.cs
  SocialNetwork/SocialNetwork.Storage/Data/SocialNetworkContext.cs
  SocialNetwork/SocialNetwork.Storage/Migrations/20241105145122_AddCommentModel.Designer.cs
  SocialNetwork/SocialNetwork.Storage/Migrations/20241105145122_AddCommentModel.cs
  SocialNetwork/SocialNetwork.Storage/Migrations/SocialNetworkContextModelSnapshot.cs
  SocialNetwork/SocialNetwork.Storage/Repository.cs
  SocialNetwork/SocialNetwork.Storage/SocialNetwork.Storage.csproj
Labels: Has migration

#23 Sn services user
  SocialNetwork/SocialNetwork.Core/Interfaces/IUserService.cs
  SocialNetwork/SocialNetwork.Core/Services/UserService.cs
Labels: Code validated

#24 Sn controllers post
  SocialNetwork/SocialNetwork.API/Controllers/PostController.cs
  SocialNetwork/SocialNetwork.API/MappingProfile.cs
  SocialNetwork/SocialNetwork.API/Program.cs
  SocialNetwork/SocialNetwork.API/SocialNetwork.API.csproj
  SocialNetwork/SocialNetwork.Core/DTOs/PostDTO.cs
Labels: Rejected

#20 Sn controllers user
  SocialNetwork/SocialNetwork.API/Controllers/UserController.cs
  SocialNetwork/SocialNetwork.API/MappingProfile.cs
  SocialNetwork/SocialNetwork.API/Program.cs
  SocialNetwork/SocialNetwork.Core/DTOs/UserDTO.cs
  SocialNetwork/SocialNetwork.Core/Models/Comment.cs
Labels: Rejected

#26 CreatePost fixed
  SocialNetwork/SocialNetwork.Core/Services/PostService.cs
Labels: Code validated, Tests passed

#30 Bug fixed
  SocialNetwork/SocialNetwork.Core/DTOs/UserDTO.cs
Labels: Code validated

#35 Login logic fix
  SocialNetwork/SocialNetwork.API/Controllers/UserController.cs
  SocialNetwork/SocialNetwork.Core/DTOs/UserLoginDTO.cs
  SocialNetwork/SocialNetwork.Core/Helpers/HashManager.cs
  SocialNetwork/SocialNetwork.Core/Interfaces/IUserService.cs
  SocialNetwork/SocialNetwork.Core/Services/UserService.cs
Labels: Code validated

#36 Bug fix: create user wrong dto [regression]
  SocialNetwork/SocialNetwork.API/Controllers/UserController.cs
Labels: Code validated

#38 Bug fix: user logout returns error
  SocialNetwork/SocialNetwork.API/Controllers/UserController.cs
Labels: Code validated

#39 Fixed
  SocialNetwork/SocialNetwork.Storage/Data/Repository.cs
Labels: Code validated

#40 bug fixed: incorect data when creating comment returns 500 code
  SocialNetwork/SocialNetwork.Core/Services/CommentService.cs
Labels: Code validated
